### ISSUE TITLE
UPLOAD Dashboard.html

### ISSUE THREAD

**Issue by salmaShahid** [Kpakpo/SpeedOps_ANPR#2]
Kindly Upload the dashboard.html file. 
Thank You

**Comment by tnkquao** [comment]
Alright. I will do that.  From: salmaShahidSent: Saturday, November 13, 2021 3:17 PMTo: Kpakpo/SpeedOps_ANPRCc: SubscribedSubject: [Kpakpo/SpeedOps_ANPR] UPLOAD Dashboard.html (Issue #2) Kindly Upload the dashboard.html file.Thank You—You are receiving this because you are subscribed to this thread.Reply to this email directly, view it on GitHub, or unsubscribe.Triage notifications on the go with GitHub Mobile for iOS or Android.
